# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'proto_01.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QGraphicsView, QLabel,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1100, 600))
        MainWindow.setMaximumSize(QSize(1100, 600))
        font = QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"../../layouts/assets/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setDocumentMode(False)
        self.actionLoadImages = QAction(MainWindow)
        self.actionLoadImages.setObjectName(u"actionLoadImages")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        font1 = QFont()
        self.actionAbout.setFont(font1)
        self.actionAbout.setAutoRepeat(False)
        self.actionAbout.setVisible(True)
        self.actionNew_Report = QAction(MainWindow)
        self.actionNew_Report.setObjectName(u"actionNew_Report")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.resizeButton = QPushButton(self.centralwidget)
        self.resizeButton.setObjectName(u"resizeButton")
        self.resizeButton.setEnabled(False)
        self.resizeButton.setGeometry(QRect(100, 520, 101, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.resizeButton.setFont(font2)
        self.imageListViewer = QListView(self.centralwidget)
        self.imageListViewer.setObjectName(u"imageListViewer")
        self.imageListViewer.setGeometry(QRect(20, 60, 271, 171))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 251, 31))
        self.label.setFont(font2)
        self.comboMethods = QComboBox(self.centralwidget)
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.setObjectName(u"comboMethods")
        self.comboMethods.setEnabled(False)
        self.comboMethods.setGeometry(QRect(20, 310, 271, 22))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        self.comboMethods.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 280, 271, 31))
        self.label_2.setFont(font3)
        self.SRBox = QCheckBox(self.centralwidget)
        self.SRBox.setObjectName(u"SRBox")
        self.SRBox.setEnabled(False)
        self.SRBox.setGeometry(QRect(20, 340, 251, 21))
        self.SRBox.setFont(font3)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(310, 40, 501, 481))
        self.graphicsView.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)
        self.graphicsView.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.FullViewportUpdate)
        self.graphicsView.setRubberBandSelectionMode(Qt.ItemSelectionMode.ContainsItemShape)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 0, 101, 31))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(520, 0, 81, 31))
        self.label_5.setFont(font4)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoImageSize = QLabel(self.centralwidget)
        self.infoImageSize.setObjectName(u"infoImageSize")
        self.infoImageSize.setGeometry(QRect(320, 530, 201, 21))
        self.infoImageSize.setFont(font2)
        self.pushButtonLoadImages = QPushButton(self.centralwidget)
        self.pushButtonLoadImages.setObjectName(u"pushButtonLoadImages")
        self.pushButtonLoadImages.setGeometry(QRect(20, 240, 81, 31))
        self.pushButtonLoadImages.setFont(font3)
        self.pushButtonDeleteImage = QPushButton(self.centralwidget)
        self.pushButtonDeleteImage.setObjectName(u"pushButtonDeleteImage")
        self.pushButtonDeleteImage.setEnabled(False)
        self.pushButtonDeleteImage.setGeometry(QRect(120, 240, 81, 31))
        self.pushButtonDeleteImage.setFont(font3)
        self.pushButtonImageZoomIn = QPushButton(self.centralwidget)
        self.pushButtonImageZoomIn.setObjectName(u"pushButtonImageZoomIn")
        self.pushButtonImageZoomIn.setEnabled(False)
        self.pushButtonImageZoomIn.setGeometry(QRect(740, 530, 31, 24))
        font5 = QFont()
        font5.setPointSize(13)
        font5.setBold(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.pushButtonImageZoomIn.setFont(font5)
        self.pushButtonImageZoomOut = QPushButton(self.centralwidget)
        self.pushButtonImageZoomOut.setObjectName(u"pushButtonImageZoomOut")
        self.pushButtonImageZoomOut.setEnabled(False)
        self.pushButtonImageZoomOut.setGeometry(QRect(780, 530, 31, 24))
        self.pushButtonImageZoomOut.setFont(font5)
        self.pushButtonDeleteAll = QPushButton(self.centralwidget)
        self.pushButtonDeleteAll.setObjectName(u"pushButtonDeleteAll")
        self.pushButtonDeleteAll.setEnabled(False)
        self.pushButtonDeleteAll.setGeometry(QRect(210, 240, 81, 31))
        self.pushButtonDeleteAll.setFont(font3)
        self.ScaleFactorBox = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox.setObjectName(u"ScaleFactorBox")
        self.ScaleFactorBox.setEnabled(False)
        self.ScaleFactorBox.setGeometry(QRect(150, 400, 61, 22))
        self.ScaleFactorBox.setFont(font3)
        self.ScaleFactorBox.setWrapping(False)
        self.ScaleFactorBox.setMinimum(0.010000000000000)
        self.ScaleFactorBox.setSingleStep(0.010000000000000)
        self.ScaleFactorBox.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox.setValue(1.000000000000000)
        self.customWidthBox = QSpinBox(self.centralwidget)
        self.customWidthBox.setObjectName(u"customWidthBox")
        self.customWidthBox.setEnabled(False)
        self.customWidthBox.setGeometry(QRect(120, 460, 71, 22))
        self.customWidthBox.setFont(font3)
        self.customHeightBox = QSpinBox(self.centralwidget)
        self.customHeightBox.setObjectName(u"customHeightBox")
        self.customHeightBox.setEnabled(False)
        self.customHeightBox.setGeometry(QRect(220, 460, 71, 22))
        self.customHeightBox.setFont(font3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 480, 71, 20))
        self.label_13.setFont(font3)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(290, -20, 20, 591))
        self.line_2.setFrameShadow(QFrame.Shadow.Raised)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(810, -20, 20, 591))
        self.line_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(840, 180, 241, 21))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.label_14.setFont(font6)
        self.label_14.setTextFormat(Qt.TextFormat.RichText)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(920, 150, 81, 21))
        self.label_15.setFont(font3)
        self.label_15.setTextFormat(Qt.TextFormat.RichText)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(840, 150, 81, 21))
        self.label_16.setFont(font3)
        self.label_16.setTextFormat(Qt.TextFormat.RichText)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(1010, 150, 81, 21))
        self.label_17.setFont(font3)
        self.label_17.setTextFormat(Qt.TextFormat.RichText)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(840, 460, 241, 21))
        self.label_18.setFont(font6)
        self.label_18.setTextFormat(Qt.TextFormat.RichText)
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(840, 250, 241, 21))
        self.label_19.setFont(font6)
        self.label_19.setTextFormat(Qt.TextFormat.RichText)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(840, 310, 241, 21))
        self.label_20.setFont(font6)
        self.label_20.setTextFormat(Qt.TextFormat.RichText)
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(840, 200, 81, 21))
        self.label_21.setFont(font3)
        self.label_21.setTextFormat(Qt.TextFormat.RichText)
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(920, 200, 81, 21))
        self.label_22.setFont(font3)
        self.label_22.setTextFormat(Qt.TextFormat.RichText)
        self.label_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(1010, 200, 81, 21))
        self.label_23.setFont(font3)
        self.label_23.setTextFormat(Qt.TextFormat.RichText)
        self.label_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(1010, 490, 81, 21))
        self.label_24.setFont(font3)
        self.label_24.setTextFormat(Qt.TextFormat.RichText)
        self.label_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(1010, 280, 81, 21))
        self.label_25.setFont(font3)
        self.label_25.setTextFormat(Qt.TextFormat.RichText)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(1010, 340, 81, 21))
        self.label_26.setFont(font3)
        self.label_26.setTextFormat(Qt.TextFormat.RichText)
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(920, 490, 81, 21))
        self.label_27.setFont(font3)
        self.label_27.setTextFormat(Qt.TextFormat.RichText)
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(920, 280, 81, 21))
        self.label_28.setFont(font3)
        self.label_28.setTextFormat(Qt.TextFormat.RichText)
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(920, 340, 81, 21))
        self.label_29.setFont(font3)
        self.label_29.setTextFormat(Qt.TextFormat.RichText)
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(840, 490, 81, 21))
        self.label_30.setFont(font3)
        self.label_30.setTextFormat(Qt.TextFormat.RichText)
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.centralwidget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(840, 280, 81, 21))
        self.label_31.setFont(font3)
        self.label_31.setTextFormat(Qt.TextFormat.RichText)
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(840, 340, 81, 21))
        self.label_32.setFont(font3)
        self.label_32.setTextFormat(Qt.TextFormat.RichText)
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(120, 480, 71, 21))
        self.label_33.setFont(font3)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.centralwidget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(190, 460, 31, 21))
        self.label_34.setFont(font3)
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.radioScaleFactor = QRadioButton(self.centralwidget)
        self.radioScaleFactor.setObjectName(u"radioScaleFactor")
        self.radioScaleFactor.setEnabled(False)
        self.radioScaleFactor.setGeometry(QRect(20, 400, 121, 20))
        self.radioScaleFactor.setFont(font3)
        self.radioScaleFactor.setChecked(True)
        self.radioCustomResolution = QRadioButton(self.centralwidget)
        self.radioCustomResolution.setObjectName(u"radioCustomResolution")
        self.radioCustomResolution.setEnabled(False)
        self.radioCustomResolution.setGeometry(QRect(20, 460, 111, 20))
        self.radioCustomResolution.setFont(font3)
        self.infoImageFormat = QLabel(self.centralwidget)
        self.infoImageFormat.setObjectName(u"infoImageFormat")
        self.infoImageFormat.setGeometry(QRect(530, 530, 201, 21))
        self.infoImageFormat.setFont(font2)
        self.radioScaleFactor_2 = QRadioButton(self.centralwidget)
        self.radioScaleFactor_2.setObjectName(u"radioScaleFactor_2")
        self.radioScaleFactor_2.setEnabled(False)
        self.radioScaleFactor_2.setGeometry(QRect(20, 430, 111, 20))
        self.radioScaleFactor_2.setFont(font3)
        self.radioScaleFactor_2.setChecked(False)
        self.ScaleFactorBox_2 = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox_2.setObjectName(u"ScaleFactorBox_2")
        self.ScaleFactorBox_2.setEnabled(False)
        self.ScaleFactorBox_2.setGeometry(QRect(150, 430, 61, 22))
        self.ScaleFactorBox_2.setFont(font3)
        self.ScaleFactorBox_2.setWrapping(False)
        self.ScaleFactorBox_2.setMinimum(0.010000000000000)
        self.ScaleFactorBox_2.setMaximum(0.990000000000000)
        self.ScaleFactorBox_2.setSingleStep(0.010000000000000)
        self.ScaleFactorBox_2.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox_2.setValue(0.990000000000000)
        self.ScaleFactorBox_3 = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox_3.setObjectName(u"ScaleFactorBox_3")
        self.ScaleFactorBox_3.setEnabled(False)
        self.ScaleFactorBox_3.setGeometry(QRect(230, 430, 61, 22))
        self.ScaleFactorBox_3.setFont(font3)
        self.ScaleFactorBox_3.setWrapping(False)
        self.ScaleFactorBox_3.setMinimum(1.010000000000000)
        self.ScaleFactorBox_3.setMaximum(128.000000000000000)
        self.ScaleFactorBox_3.setSingleStep(0.010000000000000)
        self.ScaleFactorBox_3.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox_3.setValue(1.010000000000000)
        self.label_35 = QLabel(self.centralwidget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 430, 21, 21))
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(False)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        self.label_35.setFont(font7)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.AIScaleFactorBox = QDoubleSpinBox(self.centralwidget)
        self.AIScaleFactorBox.setObjectName(u"AIScaleFactorBox")
        self.AIScaleFactorBox.setEnabled(False)
        self.AIScaleFactorBox.setGeometry(QRect(220, 340, 71, 22))
        self.AIScaleFactorBox.setFont(font3)
        self.AIScaleFactorBox.setWrapping(False)
        self.AIScaleFactorBox.setDecimals(0)
        self.AIScaleFactorBox.setMinimum(2.000000000000000)
        self.AIScaleFactorBox.setMaximum(4.000000000000000)
        self.AIScaleFactorBox.setSingleStep(1.000000000000000)
        self.AIScaleFactorBox.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.AIScaleFactorBox.setValue(2.000000000000000)
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(840, 420, 81, 21))
        self.label_36.setFont(font3)
        self.label_36.setTextFormat(Qt.TextFormat.RichText)
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.centralwidget)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(920, 420, 81, 21))
        self.label_37.setFont(font3)
        self.label_37.setTextFormat(Qt.TextFormat.RichText)
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_38 = QLabel(self.centralwidget)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(840, 390, 241, 21))
        self.label_38.setFont(font6)
        self.label_38.setTextFormat(Qt.TextFormat.RichText)
        self.label_38.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_39 = QLabel(self.centralwidget)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(1010, 420, 81, 21))
        self.label_39.setFont(font3)
        self.label_39.setTextFormat(Qt.TextFormat.RichText)
        self.label_39.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(850, 440, 221, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(850, 370, 221, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(850, 230, 221, 20))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(910, 10, 101, 21))
        font8 = QFont()
        font8.setPointSize(13)
        font8.setBold(True)
        font8.setUnderline(False)
        font8.setStrikeOut(False)
        font8.setKerning(True)
        self.label_6.setFont(font8)
        self.label_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.numResizedImages = QLabel(self.centralwidget)
        self.numResizedImages.setObjectName(u"numResizedImages")
        self.numResizedImages.setGeometry(QRect(840, 40, 131, 21))
        self.numResizedImages.setFont(font3)
        self.chosenMethod = QLabel(self.centralwidget)
        self.chosenMethod.setObjectName(u"chosenMethod")
        self.chosenMethod.setGeometry(QRect(840, 70, 131, 21))
        self.chosenMethod.setFont(font3)
        self.chosenScale = QLabel(self.centralwidget)
        self.chosenScale.setObjectName(u"chosenScale")
        self.chosenScale.setGeometry(QRect(840, 100, 131, 21))
        self.chosenScale.setFont(font3)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(850, 130, 221, 16))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuInfo = QMenu(self.menubar)
        self.menuInfo.setObjectName(u"menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menuFile.addAction(self.actionLoadImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuInfo.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Image Resizer", None))
        self.actionLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionNew_Report.setText(QCoreApplication.translate("MainWindow", u"New Report", None))
        self.resizeButton.setText(QCoreApplication.translate("MainWindow", u"Resize", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Loaded images", None))
        self.comboMethods.setItemText(0, QCoreApplication.translate("MainWindow", u"Nearest Neighbor", None))
        self.comboMethods.setItemText(1, QCoreApplication.translate("MainWindow", u"Bilinear", None))
        self.comboMethods.setItemText(2, QCoreApplication.translate("MainWindow", u"Bicubic", None))
        self.comboMethods.setItemText(3, QCoreApplication.translate("MainWindow", u"Spline", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Interpolation method", None))
        self.SRBox.setText(QCoreApplication.translate("MainWindow", u"Use super-resolution (EDSR)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Input", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.infoImageSize.setText(QCoreApplication.translate("MainWindow", u"Size:", None))
        self.pushButtonLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.pushButtonDeleteImage.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButtonImageZoomIn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButtonImageZoomOut.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButtonDeleteAll.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Process Time", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"AVG", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"MIN", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"MAX", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"MAE", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"PSNR", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"SSIM", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.radioScaleFactor.setText(QCoreApplication.translate("MainWindow", u"One-way scale", None))
        self.radioCustomResolution.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.infoImageFormat.setText(QCoreApplication.translate("MainWindow", u"Format:", None))
        self.radioScaleFactor_2.setText(QCoreApplication.translate("MainWindow", u"Reconstruction", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Edge", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.numResizedImages.setText(QCoreApplication.translate("MainWindow", u"Resized images:", None))
        self.chosenMethod.setText(QCoreApplication.translate("MainWindow", u"Method:", None))
        self.chosenScale.setText(QCoreApplication.translate("MainWindow", u"Scale:", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuInfo.setTitle(QCoreApplication.translate("MainWindow", u"Info", None))
    # retranslateUi

