# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'proto_01.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QGraphicsView, QLabel,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 650)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1100, 600))
        MainWindow.setMaximumSize(QSize(1100, 650))
        font = QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"C:/Users/skala/layouts/assets/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setDocumentMode(False)
        self.actionLoadImages = QAction(MainWindow)
        self.actionLoadImages.setObjectName(u"actionLoadImages")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        font1 = QFont()
        self.actionAbout.setFont(font1)
        self.actionAbout.setAutoRepeat(False)
        self.actionAbout.setVisible(True)
        self.actionNew_Report = QAction(MainWindow)
        self.actionNew_Report.setObjectName(u"actionNew_Report")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.resizeButton = QPushButton(self.centralwidget)
        self.resizeButton.setObjectName(u"resizeButton")
        self.resizeButton.setEnabled(False)
        self.resizeButton.setGeometry(QRect(50, 560, 101, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.resizeButton.setFont(font2)
        self.imageListViewer = QListView(self.centralwidget)
        self.imageListViewer.setObjectName(u"imageListViewer")
        self.imageListViewer.setGeometry(QRect(10, 60, 281, 171))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 251, 21))
        self.label.setFont(font2)
        self.comboMethods = QComboBox(self.centralwidget)
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.setObjectName(u"comboMethods")
        self.comboMethods.setEnabled(False)
        self.comboMethods.setGeometry(QRect(10, 311, 281, 21))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        self.comboMethods.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 290, 281, 21))
        self.label_2.setFont(font3)
        self.SRBox = QCheckBox(self.centralwidget)
        self.SRBox.setObjectName(u"SRBox")
        self.SRBox.setEnabled(False)
        self.SRBox.setGeometry(QRect(10, 340, 121, 21))
        self.SRBox.setFont(font3)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(310, 40, 501, 261))
        self.graphicsView.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)
        self.graphicsView.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.FullViewportUpdate)
        self.graphicsView.setRubberBandSelectionMode(Qt.ItemSelectionMode.ContainsItemShape)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 0, 101, 31))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(520, 0, 81, 31))
        self.label_5.setFont(font4)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoImageSize = QLabel(self.centralwidget)
        self.infoImageSize.setObjectName(u"infoImageSize")
        self.infoImageSize.setGeometry(QRect(310, 580, 201, 21))
        self.infoImageSize.setFont(font2)
        self.pushButtonLoadImages = QPushButton(self.centralwidget)
        self.pushButtonLoadImages.setObjectName(u"pushButtonLoadImages")
        self.pushButtonLoadImages.setGeometry(QRect(10, 240, 91, 31))
        self.pushButtonLoadImages.setFont(font2)
        self.pushButtonDeleteImage = QPushButton(self.centralwidget)
        self.pushButtonDeleteImage.setObjectName(u"pushButtonDeleteImage")
        self.pushButtonDeleteImage.setEnabled(False)
        self.pushButtonDeleteImage.setGeometry(QRect(120, 240, 81, 31))
        self.pushButtonDeleteImage.setFont(font2)
        self.pushButtonImageZoomIn = QPushButton(self.centralwidget)
        self.pushButtonImageZoomIn.setObjectName(u"pushButtonImageZoomIn")
        self.pushButtonImageZoomIn.setEnabled(False)
        self.pushButtonImageZoomIn.setGeometry(QRect(740, 580, 31, 24))
        font5 = QFont()
        font5.setPointSize(13)
        font5.setBold(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.pushButtonImageZoomIn.setFont(font5)
        self.pushButtonImageZoomOut = QPushButton(self.centralwidget)
        self.pushButtonImageZoomOut.setObjectName(u"pushButtonImageZoomOut")
        self.pushButtonImageZoomOut.setEnabled(False)
        self.pushButtonImageZoomOut.setGeometry(QRect(780, 580, 31, 24))
        self.pushButtonImageZoomOut.setFont(font5)
        self.pushButtonDeleteAll = QPushButton(self.centralwidget)
        self.pushButtonDeleteAll.setObjectName(u"pushButtonDeleteAll")
        self.pushButtonDeleteAll.setEnabled(False)
        self.pushButtonDeleteAll.setGeometry(QRect(210, 240, 81, 31))
        self.pushButtonDeleteAll.setFont(font2)
        self.ScaleFactorBox = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox.setObjectName(u"ScaleFactorBox")
        self.ScaleFactorBox.setEnabled(False)
        self.ScaleFactorBox.setGeometry(QRect(150, 390, 61, 22))
        self.ScaleFactorBox.setFont(font3)
        self.ScaleFactorBox.setWrapping(False)
        self.ScaleFactorBox.setMinimum(0.010000000000000)
        self.ScaleFactorBox.setSingleStep(0.010000000000000)
        self.ScaleFactorBox.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox.setValue(1.000000000000000)
        self.customWidthBox = QSpinBox(self.centralwidget)
        self.customWidthBox.setObjectName(u"customWidthBox")
        self.customWidthBox.setEnabled(False)
        self.customWidthBox.setGeometry(QRect(120, 470, 71, 22))
        self.customWidthBox.setFont(font3)
        self.customWidthBox.setMaximum(1000000)
        self.customWidthBox.setSingleStep(10)
        self.customHeightBox = QSpinBox(self.centralwidget)
        self.customHeightBox.setObjectName(u"customHeightBox")
        self.customHeightBox.setEnabled(False)
        self.customHeightBox.setGeometry(QRect(220, 470, 71, 22))
        self.customHeightBox.setFont(font3)
        self.customHeightBox.setMaximum(1000000)
        self.customHeightBox.setSingleStep(10)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 490, 71, 20))
        self.label_13.setFont(font3)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(290, -20, 20, 591))
        self.line_2.setFrameShadow(QFrame.Shadow.Raised)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(810, -20, 20, 591))
        self.line_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(840, 400, 241, 21))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.label_14.setFont(font6)
        self.label_14.setTextFormat(Qt.TextFormat.RichText)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(920, 260, 81, 21))
        self.label_15.setFont(font3)
        self.label_15.setTextFormat(Qt.TextFormat.RichText)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(840, 260, 81, 21))
        self.label_16.setFont(font3)
        self.label_16.setTextFormat(Qt.TextFormat.RichText)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(1010, 260, 81, 21))
        self.label_17.setFont(font3)
        self.label_17.setTextFormat(Qt.TextFormat.RichText)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(840, 450, 241, 21))
        self.label_19.setFont(font6)
        self.label_19.setTextFormat(Qt.TextFormat.RichText)
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(840, 510, 241, 21))
        self.label_20.setFont(font6)
        self.label_20.setTextFormat(Qt.TextFormat.RichText)
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoMSEMin = QLabel(self.centralwidget)
        self.infoMSEMin.setObjectName(u"infoMSEMin")
        self.infoMSEMin.setGeometry(QRect(840, 420, 81, 21))
        self.infoMSEMin.setFont(font2)
        self.infoMSEMin.setTextFormat(Qt.TextFormat.RichText)
        self.infoMSEMin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoMSEAvg = QLabel(self.centralwidget)
        self.infoMSEAvg.setObjectName(u"infoMSEAvg")
        self.infoMSEAvg.setGeometry(QRect(920, 420, 81, 21))
        self.infoMSEAvg.setFont(font2)
        self.infoMSEAvg.setTextFormat(Qt.TextFormat.RichText)
        self.infoMSEAvg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoMSEMax = QLabel(self.centralwidget)
        self.infoMSEMax.setObjectName(u"infoMSEMax")
        self.infoMSEMax.setGeometry(QRect(1010, 420, 81, 21))
        self.infoMSEMax.setFont(font2)
        self.infoMSEMax.setTextFormat(Qt.TextFormat.RichText)
        self.infoMSEMax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoPSNRMax = QLabel(self.centralwidget)
        self.infoPSNRMax.setObjectName(u"infoPSNRMax")
        self.infoPSNRMax.setGeometry(QRect(1010, 470, 81, 21))
        self.infoPSNRMax.setFont(font2)
        self.infoPSNRMax.setTextFormat(Qt.TextFormat.RichText)
        self.infoPSNRMax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoSSIMMax = QLabel(self.centralwidget)
        self.infoSSIMMax.setObjectName(u"infoSSIMMax")
        self.infoSSIMMax.setGeometry(QRect(1010, 530, 81, 21))
        self.infoSSIMMax.setFont(font2)
        self.infoSSIMMax.setTextFormat(Qt.TextFormat.RichText)
        self.infoSSIMMax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoPSNRAvg = QLabel(self.centralwidget)
        self.infoPSNRAvg.setObjectName(u"infoPSNRAvg")
        self.infoPSNRAvg.setGeometry(QRect(920, 470, 81, 21))
        self.infoPSNRAvg.setFont(font2)
        self.infoPSNRAvg.setTextFormat(Qt.TextFormat.RichText)
        self.infoPSNRAvg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoSSIMAvg = QLabel(self.centralwidget)
        self.infoSSIMAvg.setObjectName(u"infoSSIMAvg")
        self.infoSSIMAvg.setGeometry(QRect(920, 530, 81, 21))
        self.infoSSIMAvg.setFont(font2)
        self.infoSSIMAvg.setTextFormat(Qt.TextFormat.RichText)
        self.infoSSIMAvg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoPSNRMin = QLabel(self.centralwidget)
        self.infoPSNRMin.setObjectName(u"infoPSNRMin")
        self.infoPSNRMin.setGeometry(QRect(840, 470, 81, 21))
        self.infoPSNRMin.setFont(font2)
        self.infoPSNRMin.setTextFormat(Qt.TextFormat.RichText)
        self.infoPSNRMin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoSSIMMin = QLabel(self.centralwidget)
        self.infoSSIMMin.setObjectName(u"infoSSIMMin")
        self.infoSSIMMin.setGeometry(QRect(840, 530, 81, 21))
        self.infoSSIMMin.setFont(font2)
        self.infoSSIMMin.setTextFormat(Qt.TextFormat.RichText)
        self.infoSSIMMin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(120, 490, 71, 21))
        self.label_33.setFont(font3)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.centralwidget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(190, 470, 31, 21))
        self.label_34.setFont(font2)
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.radioScaleFactor = QRadioButton(self.centralwidget)
        self.radioScaleFactor.setObjectName(u"radioScaleFactor")
        self.radioScaleFactor.setEnabled(False)
        self.radioScaleFactor.setGeometry(QRect(20, 390, 131, 20))
        self.radioScaleFactor.setFont(font2)
        self.radioScaleFactor.setChecked(True)
        self.radioCustomResolution = QRadioButton(self.centralwidget)
        self.radioCustomResolution.setObjectName(u"radioCustomResolution")
        self.radioCustomResolution.setEnabled(False)
        self.radioCustomResolution.setGeometry(QRect(20, 470, 101, 20))
        self.radioCustomResolution.setFont(font2)
        self.radioScaleFactor_2 = QRadioButton(self.centralwidget)
        self.radioScaleFactor_2.setObjectName(u"radioScaleFactor_2")
        self.radioScaleFactor_2.setEnabled(False)
        self.radioScaleFactor_2.setGeometry(QRect(20, 430, 121, 20))
        self.radioScaleFactor_2.setFont(font2)
        self.radioScaleFactor_2.setChecked(False)
        self.ScaleFactorBox_2 = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox_2.setObjectName(u"ScaleFactorBox_2")
        self.ScaleFactorBox_2.setEnabled(False)
        self.ScaleFactorBox_2.setGeometry(QRect(150, 430, 61, 22))
        self.ScaleFactorBox_2.setFont(font3)
        self.ScaleFactorBox_2.setWrapping(False)
        self.ScaleFactorBox_2.setMinimum(0.010000000000000)
        self.ScaleFactorBox_2.setMaximum(1.000000000000000)
        self.ScaleFactorBox_2.setSingleStep(0.010000000000000)
        self.ScaleFactorBox_2.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox_2.setValue(1.000000000000000)
        self.ScaleFactorBox_3 = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox_3.setObjectName(u"ScaleFactorBox_3")
        self.ScaleFactorBox_3.setEnabled(False)
        self.ScaleFactorBox_3.setGeometry(QRect(230, 430, 61, 22))
        self.ScaleFactorBox_3.setFont(font3)
        self.ScaleFactorBox_3.setWrapping(False)
        self.ScaleFactorBox_3.setMinimum(1.000000000000000)
        self.ScaleFactorBox_3.setMaximum(128.000000000000000)
        self.ScaleFactorBox_3.setSingleStep(0.010000000000000)
        self.ScaleFactorBox_3.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox_3.setValue(1.000000000000000)
        self.label_35 = QLabel(self.centralwidget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 430, 21, 21))
        self.label_35.setFont(font3)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.AIScaleFactorBox = QDoubleSpinBox(self.centralwidget)
        self.AIScaleFactorBox.setObjectName(u"AIScaleFactorBox")
        self.AIScaleFactorBox.setEnabled(False)
        self.AIScaleFactorBox.setGeometry(QRect(250, 340, 41, 22))
        self.AIScaleFactorBox.setFont(font3)
        self.AIScaleFactorBox.setWrapping(False)
        self.AIScaleFactorBox.setDecimals(0)
        self.AIScaleFactorBox.setMinimum(2.000000000000000)
        self.AIScaleFactorBox.setMaximum(4.000000000000000)
        self.AIScaleFactorBox.setSingleStep(1.000000000000000)
        self.AIScaleFactorBox.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.AIScaleFactorBox.setValue(2.000000000000000)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(910, 10, 101, 21))
        font7 = QFont()
        font7.setPointSize(13)
        font7.setBold(True)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        font7.setKerning(True)
        self.label_6.setFont(font7)
        self.label_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(850, 240, 221, 16))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(830, 40, 251, 21))
        self.label_3.setFont(font2)
        self.imageListViewer_2 = QListView(self.centralwidget)
        self.imageListViewer_2.setObjectName(u"imageListViewer_2")
        self.imageListViewer_2.setGeometry(QRect(830, 70, 261, 171))
        self.infoProcessTimeMin = QLabel(self.centralwidget)
        self.infoProcessTimeMin.setObjectName(u"infoProcessTimeMin")
        self.infoProcessTimeMin.setGeometry(QRect(840, 320, 81, 21))
        self.infoProcessTimeMin.setFont(font2)
        self.infoProcessTimeMin.setTextFormat(Qt.TextFormat.RichText)
        self.infoProcessTimeMin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(840, 290, 241, 21))
        self.label_18.setFont(font6)
        self.label_18.setTextFormat(Qt.TextFormat.RichText)
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoProcessTimeMax = QLabel(self.centralwidget)
        self.infoProcessTimeMax.setObjectName(u"infoProcessTimeMax")
        self.infoProcessTimeMax.setGeometry(QRect(1010, 320, 81, 21))
        self.infoProcessTimeMax.setFont(font2)
        self.infoProcessTimeMax.setTextFormat(Qt.TextFormat.RichText)
        self.infoProcessTimeMax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoProcessTimeAvg = QLabel(self.centralwidget)
        self.infoProcessTimeAvg.setObjectName(u"infoProcessTimeAvg")
        self.infoProcessTimeAvg.setGeometry(QRect(920, 320, 81, 21))
        self.infoProcessTimeAvg.setFont(font2)
        self.infoProcessTimeAvg.setTextFormat(Qt.TextFormat.RichText)
        self.infoProcessTimeAvg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.SRBox_Model = QComboBox(self.centralwidget)
        self.SRBox_Model.addItem("")
        self.SRBox_Model.addItem("")
        self.SRBox_Model.addItem("")
        self.SRBox_Model.addItem("")
        self.SRBox_Model.setObjectName(u"SRBox_Model")
        self.SRBox_Model.setEnabled(False)
        self.SRBox_Model.setGeometry(QRect(140, 340, 91, 22))
        self.SRBox_Model.setFont(font3)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 340, 21, 21))
        self.label_7.setFont(font3)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 360, 71, 21))
        self.label_8.setFont(font3)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(230, 360, 71, 21))
        self.label_9.setFont(font3)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.clearButton = QPushButton(self.centralwidget)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setEnabled(False)
        self.clearButton.setGeometry(QRect(910, 570, 101, 31))
        self.clearButton.setFont(font2)
        self.CSVBox = QCheckBox(self.centralwidget)
        self.CSVBox.setObjectName(u"CSVBox")
        self.CSVBox.setEnabled(False)
        self.CSVBox.setGeometry(QRect(30, 530, 131, 31))
        self.CSVBox.setFont(font3)
        self.CSVBox.setChecked(True)
        self.outputFormatBox = QComboBox(self.centralwidget)
        self.outputFormatBox.addItem("")
        self.outputFormatBox.addItem("")
        self.outputFormatBox.addItem("")
        self.outputFormatBox.addItem("")
        self.outputFormatBox.setObjectName(u"outputFormatBox")
        self.outputFormatBox.setEnabled(False)
        self.outputFormatBox.setGeometry(QRect(190, 560, 81, 21))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 530, 101, 31))
        self.label_10.setFont(font3)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graphicsView_2 = QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(310, 310, 501, 261))
        self.graphicsView_2.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)
        self.graphicsView_2.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView_2.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.FullViewportUpdate)
        self.graphicsView_2.setRubberBandSelectionMode(Qt.ItemSelectionMode.ContainsItemShape)
        self.infoImageSize_2 = QLabel(self.centralwidget)
        self.infoImageSize_2.setObjectName(u"infoImageSize_2")
        self.infoImageSize_2.setGeometry(QRect(520, 580, 201, 21))
        self.infoImageSize_2.setFont(font2)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(840, 340, 241, 21))
        self.label_21.setFont(font6)
        self.label_21.setTextFormat(Qt.TextFormat.RichText)
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoThroughputAvg = QLabel(self.centralwidget)
        self.infoThroughputAvg.setObjectName(u"infoThroughputAvg")
        self.infoThroughputAvg.setGeometry(QRect(920, 370, 81, 21))
        self.infoThroughputAvg.setFont(font2)
        self.infoThroughputAvg.setTextFormat(Qt.TextFormat.RichText)
        self.infoThroughputAvg.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoThroughputMax = QLabel(self.centralwidget)
        self.infoThroughputMax.setObjectName(u"infoThroughputMax")
        self.infoThroughputMax.setGeometry(QRect(1010, 370, 81, 21))
        self.infoThroughputMax.setFont(font2)
        self.infoThroughputMax.setTextFormat(Qt.TextFormat.RichText)
        self.infoThroughputMax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.infoThroughputMin = QLabel(self.centralwidget)
        self.infoThroughputMin.setObjectName(u"infoThroughputMin")
        self.infoThroughputMin.setGeometry(QRect(840, 370, 81, 21))
        self.infoThroughputMin.setFont(font2)
        self.infoThroughputMin.setTextFormat(Qt.TextFormat.RichText)
        self.infoThroughputMin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuInfo = QMenu(self.menubar)
        self.menuInfo.setObjectName(u"menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menuFile.addAction(self.actionLoadImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuInfo.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Image Resizer", None))
        self.actionLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionNew_Report.setText(QCoreApplication.translate("MainWindow", u"New Report", None))
        self.resizeButton.setText(QCoreApplication.translate("MainWindow", u"Resize", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Loaded images (up to 100 images)", None))
        self.comboMethods.setItemText(0, QCoreApplication.translate("MainWindow", u"Nearest Neighbor", None))
        self.comboMethods.setItemText(1, QCoreApplication.translate("MainWindow", u"Bilinear", None))
        self.comboMethods.setItemText(2, QCoreApplication.translate("MainWindow", u"Bicubic", None))
        self.comboMethods.setItemText(3, QCoreApplication.translate("MainWindow", u"Lanczos", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Interpolation method", None))
        self.SRBox.setText(QCoreApplication.translate("MainWindow", u"Super-resolution", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Input", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Images", None))
        self.infoImageSize.setText(QCoreApplication.translate("MainWindow", u"Size (Input):", None))
        self.pushButtonLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.pushButtonDeleteImage.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButtonImageZoomIn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButtonImageZoomOut.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButtonDeleteAll.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"MSE", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"AVG", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"MIN", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"MAX", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"PSNR (dB)", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"SSIM (0-1)", None))
        self.infoMSEMin.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoMSEAvg.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoMSEMax.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoPSNRMax.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoSSIMMax.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoPSNRAvg.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoSSIMAvg.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoPSNRMin.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoSSIMMin.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.radioScaleFactor.setText(QCoreApplication.translate("MainWindow", u"One-way scale", None))
        self.radioCustomResolution.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.radioScaleFactor_2.setText(QCoreApplication.translate("MainWindow", u"Reconstruction", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Processed images", None))
        self.infoProcessTimeMin.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Process Time (s)", None))
        self.infoProcessTimeMax.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoProcessTimeAvg.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.SRBox_Model.setItemText(0, QCoreApplication.translate("MainWindow", u"EDSR", None))
        self.SRBox_Model.setItemText(1, QCoreApplication.translate("MainWindow", u"ESPCN", None))
        self.SRBox_Model.setItemText(2, QCoreApplication.translate("MainWindow", u"FSRCNN", None))
        self.SRBox_Model.setItemText(3, QCoreApplication.translate("MainWindow", u"LapSRN", None))

        self.label_7.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Scale", None))
        self.clearButton.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.CSVBox.setText(QCoreApplication.translate("MainWindow", u"Save results in CSV", None))
        self.outputFormatBox.setItemText(0, QCoreApplication.translate("MainWindow", u"PNG", None))
        self.outputFormatBox.setItemText(1, QCoreApplication.translate("MainWindow", u"TIFF", None))
        self.outputFormatBox.setItemText(2, QCoreApplication.translate("MainWindow", u"BMP", None))
        self.outputFormatBox.setItemText(3, QCoreApplication.translate("MainWindow", u"JPG", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Output Format", None))
        self.infoImageSize_2.setText(QCoreApplication.translate("MainWindow", u"Size (Output):", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Throughput (MP/s)", None))
        self.infoThroughputAvg.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoThroughputMax.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.infoThroughputMin.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuInfo.setTitle(QCoreApplication.translate("MainWindow", u"Info", None))
    # retranslateUi

