# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'proto_01.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QGraphicsView, QLabel,
    QListView, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollBar, QSizePolicy, QSpinBox,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1100, 600))
        MainWindow.setMaximumSize(QSize(1100, 600))
        font = QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"assets/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setDocumentMode(False)
        self.actionLoadImages = QAction(MainWindow)
        self.actionLoadImages.setObjectName(u"actionLoadImages")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        font1 = QFont()
        self.actionAbout.setFont(font1)
        self.actionAbout.setAutoRepeat(False)
        self.actionAbout.setVisible(True)
        self.actionNew_Report = QAction(MainWindow)
        self.actionNew_Report.setObjectName(u"actionNew_Report")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.resizeButton = QPushButton(self.centralwidget)
        self.resizeButton.setObjectName(u"resizeButton")
        self.resizeButton.setEnabled(False)
        self.resizeButton.setGeometry(QRect(100, 510, 101, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.resizeButton.setFont(font2)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(910, 500, 101, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        self.pushButton_2.setFont(font3)
        self.imageListViewer = QListView(self.centralwidget)
        self.imageListViewer.setObjectName(u"imageListViewer")
        self.imageListViewer.setGeometry(QRect(20, 60, 251, 191))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 40, 251, 21))
        self.label.setFont(font3)
        self.comboMethods = QComboBox(self.centralwidget)
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.addItem("")
        self.comboMethods.setObjectName(u"comboMethods")
        self.comboMethods.setEnabled(False)
        self.comboMethods.setGeometry(QRect(20, 360, 261, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 330, 251, 31))
        self.label_2.setFont(font3)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QRect(20, 300, 251, 31))
        self.checkBox.setFont(font3)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(310, 40, 500, 481))
        self.graphicsView.setDragMode(QGraphicsView.DragMode.ScrollHandDrag)
        self.graphicsView.setResizeAnchor(QGraphicsView.ViewportAnchor.NoAnchor)
        self.graphicsView.setViewportUpdateMode(QGraphicsView.ViewportUpdateMode.FullViewportUpdate)
        self.graphicsView.setRubberBandSelectionMode(Qt.ItemSelectionMode.ContainsItemShape)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(910, 0, 111, 31))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        font4.setKerning(True)
        self.label_3.setFont(font4)
        self.label_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 0, 101, 31))
        font5 = QFont()
        font5.setPointSize(13)
        font5.setBold(True)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.label_4.setFont(font5)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(520, 0, 81, 31))
        self.label_5.setFont(font5)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(820, 40, 81, 21))
        self.label_6.setFont(font3)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(920, 80, 81, 21))
        font6 = QFont()
        font6.setPointSize(9)
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.label_7.setFont(font6)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(830, 110, 131, 21))
        self.label_8.setFont(font3)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(960, 110, 131, 21))
        self.label_9.setFont(font3)
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QRect(880, 110, 71, 22))
        self.spinBox.setReadOnly(True)
        self.spinBox.setMaximum(200000)
        self.spinBox_2 = QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QRect(1010, 110, 71, 22))
        self.spinBox_2.setReadOnly(True)
        self.spinBox_2.setMaximum(200000)
        self.verticalScrollBar = QScrollBar(self.centralwidget)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setGeometry(QRect(270, 60, 21, 191))
        self.verticalScrollBar.setOrientation(Qt.Orientation.Vertical)
        self.pushButtonLoadImages = QPushButton(self.centralwidget)
        self.pushButtonLoadImages.setObjectName(u"pushButtonLoadImages")
        self.pushButtonLoadImages.setGeometry(QRect(20, 260, 71, 31))
        self.pushButtonLoadImages.setFont(font3)
        self.pushButtonDeleteImage = QPushButton(self.centralwidget)
        self.pushButtonDeleteImage.setObjectName(u"pushButtonDeleteImage")
        self.pushButtonDeleteImage.setEnabled(False)
        self.pushButtonDeleteImage.setGeometry(QRect(110, 260, 71, 31))
        self.pushButtonDeleteImage.setFont(font3)
        self.pushButtonImageZoomIn = QPushButton(self.centralwidget)
        self.pushButtonImageZoomIn.setObjectName(u"pushButtonImageZoomIn")
        self.pushButtonImageZoomIn.setEnabled(False)
        self.pushButtonImageZoomIn.setGeometry(QRect(740, 530, 31, 24))
        font7 = QFont()
        font7.setPointSize(13)
        font7.setBold(False)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        self.pushButtonImageZoomIn.setFont(font7)
        self.pushButtonImageZoomOut = QPushButton(self.centralwidget)
        self.pushButtonImageZoomOut.setObjectName(u"pushButtonImageZoomOut")
        self.pushButtonImageZoomOut.setEnabled(False)
        self.pushButtonImageZoomOut.setGeometry(QRect(780, 530, 31, 24))
        self.pushButtonImageZoomOut.setFont(font7)
        self.pushButtonDeleteAll = QPushButton(self.centralwidget)
        self.pushButtonDeleteAll.setObjectName(u"pushButtonDeleteAll")
        self.pushButtonDeleteAll.setEnabled(False)
        self.pushButtonDeleteAll.setGeometry(QRect(200, 260, 71, 31))
        self.pushButtonDeleteAll.setFont(font3)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 400, 81, 31))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(True)
        font8.setUnderline(False)
        font8.setStrikeOut(False)
        self.label_10.setFont(font8)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ScaleFactorBox = QDoubleSpinBox(self.centralwidget)
        self.ScaleFactorBox.setObjectName(u"ScaleFactorBox")
        self.ScaleFactorBox.setEnabled(False)
        self.ScaleFactorBox.setGeometry(QRect(30, 460, 61, 22))
        self.ScaleFactorBox.setWrapping(False)
        self.ScaleFactorBox.setMinimum(0.010000000000000)
        self.ScaleFactorBox.setSingleStep(0.010000000000000)
        self.ScaleFactorBox.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.ScaleFactorBox.setValue(1.000000000000000)
        self.customWidthBox = QSpinBox(self.centralwidget)
        self.customWidthBox.setObjectName(u"customWidthBox")
        self.customWidthBox.setEnabled(False)
        self.customWidthBox.setGeometry(QRect(120, 460, 71, 22))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(140, 400, 121, 31))
        self.label_11.setFont(font8)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(120, 430, 71, 31))
        self.label_12.setFont(font3)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.customHeightBox = QSpinBox(self.centralwidget)
        self.customHeightBox.setObjectName(u"customHeightBox")
        self.customHeightBox.setEnabled(False)
        self.customHeightBox.setGeometry(QRect(220, 460, 71, 22))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 430, 71, 31))
        self.label_13.setFont(font3)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(100, 400, 16, 81))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(900, 40, 181, 41))
        self.label_14.setFont(font3)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTop|Qt.AlignmentFlag.AlignTrailing)
        self.label_14.setWordWrap(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuInfo = QMenu(self.menubar)
        self.menuInfo.setObjectName(u"menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menuFile.addAction(self.actionLoadImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuInfo.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Image Resizer", None))
        self.actionLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionNew_Report.setText(QCoreApplication.translate("MainWindow", u"New Report", None))
        self.resizeButton.setText(QCoreApplication.translate("MainWindow", u"Resize", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"GetReport", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Loaded images", None))
        self.comboMethods.setItemText(0, QCoreApplication.translate("MainWindow", u"Nearest Neighbor", None))
        self.comboMethods.setItemText(1, QCoreApplication.translate("MainWindow", u"Bilinear", None))
        self.comboMethods.setItemText(2, QCoreApplication.translate("MainWindow", u"Bicubic", None))
        self.comboMethods.setItemText(3, QCoreApplication.translate("MainWindow", u"Spline", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Interpolation method", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Use super-resolution (AI)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Stats", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Input", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Image name:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Info details", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Height:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Width:", None))
        self.pushButtonLoadImages.setText(QCoreApplication.translate("MainWindow", u"Load...", None))
        self.pushButtonDeleteImage.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButtonImageZoomIn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButtonImageZoomOut.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButtonDeleteAll.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Scale Factor", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Custom Resolution", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.label_14.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuInfo.setTitle(QCoreApplication.translate("MainWindow", u"Info", None))
    # retranslateUi

